### ISSUE TITLE
Players cant open doors

### ISSUE THREAD

**Issue by harrytemp78** [wargamer/SignShopHotel#5]
When players rent out rooms they cant open the door, is it because i have essentials anitbuild installed?

**Comment by weaves7** [comment]
Do you mean the renter or the owner cannot open the door? Are there any messages or errors in console or chat? Is the sign owner opped? Are you near spawn where spawn protection could be stopping them?  Do you have all of the essentials signs disabled? Please pastebin your latest.log.

**Comment by harrytemp78** [comment]
I don’t have access to my log atm as the log clears its self when it shuts down (I got a free server). The players are not opped they can rent the room but the door to the room won’t open. I’m getting the world guard saying hey your can use that here. If I set it so they can open doors it would mean they could open every door. I would only like the owner of the room to open the door

**Comment by weaves7** [comment]
> I don’t have access to my log atm as the log clears its self when it shuts down (I got a free server). The players are not opped they can rent the room but the door to the room won’t open. I’m getting the world guard saying hey your can use that here. If I set it so they can open doors it would mean they could open every door. I would only like the owner of the room to open the door

Have you tried allowing them to open the doors with world guard? SignShopHotel should stop players from opening doors that they don't own or rent.

**Comment by harrytemp78** [comment]
Thank you! It now works!
